const UserEvent = {
  GET_ALL_USERS: "GET_ALL_USERS",
  INSERT_ONE_USER: "INSERT_ONE_USER",
  RESULT_GET_ALL_USER: "RESULT_GET_ALL_USER",
};

const WinEvent = {
  WIN_CLOSE: "WIN_CLOSE",
  WIN_ZOOM: "WIN_ZOOM",
  WIN_MINIMIZE: "WIN_MINIMIZE",
  IS_MAXIMIZED: "IS_MAXIMIZED",
  WIN_SIZE: "WIN_SIZE",
};

module.exports = {
  UserEvent,
  WinEvent,
};
