const UserEvent = {
  GET_ALL_USERS: "GET_ALL_USERS",
  INSERT_ONE_USER: "INSERT_ONE_USER",
  RESULT_GET_ALL_USER: "RESULT_GET_ALL_USER",
};

const CompanyEvent = {
  GET_ALL_COMPANIES: "GET_ALL_COMPANIES",
  GET_ONE_COMPANY: "GET_ONE_COMPANY",
  INSERT_ONE_COMPANY: "INSERT_ONE_COMPANY",
  UPDATE_ONE_COMPANY: "UPDATE_ONE_COMPANY",
  DELETE_ONE_COMPANY: "DELETE_ONE_COMPANY",

  RESULT_GET_ALL_COMPANIES: "RESULT_GET_ALL_COMPANIES",
  RESULT_GET_ONE_COMPANY: "RESULT_GET_ONE_COMPANY",
  RESULT_INSERT_ONE_COMPANY: "RESULT_INSERT_ONE_COMPANY",
  RESULT_UPDATE_ONE_COMPANY: "RESULT_UPDATE_ONE_COMPANY",
  RESULT_DELETE_ONE_COMPANY: "RESULT_DELETE_ONE_COMPANY",
};

const InvoiceEvent = {
  GET_ALL_INVOICES: "GET_ALL_INVOICES",
  GET_ONE_INVOICE: "GET_ONE_INVOICE",
  INSERT_ONE_INVOICE: "INSERT_ONE_INVOICE",
  UPDATE_ONE_INVOICE: "UPDATE_ONE_INVOICE",
  DELETE_ONE_INVOICE: "DELETE_ONE_INVOICE",

  RESULT_GET_ALL_INVOICES: "RESULT_GET_ALL_INVOICES",
  RESULT_GET_ONE_INVOICE: "RESULT_GET_ONE_INVOICE",
  RESULT_INSERT_ONE_INVOICE: "RESULT_INSERT_ONE_INVOICE",
  RESULT_UPDATE_ONE_INVOICE: "RESULT_UPDATE_ONE_INVOICE",
  RESULT_DELETE_ONE_INVOICE: "RESULT_DELETE_ONE_INVOICE",
};

const MediaEvent = {
  STORE_MEDIA: "STORE_MEDIA",

  RESULT_STORE_MEDIA: "RESULT_STORE_MEDIA",
};

module.exports = {
  UserEvent,
  CompanyEvent,
  InvoiceEvent,
  MediaEvent,
};